version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1
filters: &filters
  tags:
    only: /.*/
environment:
  ORB_PARAM_ORB_PUB_TOKEN: $CIRCLE_TOKEN
workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086,SC2002,SC2016
          filters: *filters
      - orb-tools/publish:
          orb-name: a11ywatch/a11ywatch
          vcs-type: github
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
          context:
            - a11ywatch
          filters: *filters
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: github
          requires: [orb-tools/publish]
          filters: *filters
